### ISSUE TITLE
Bug: function that database

### ISSUE THREAD

**Issue by cambo2015** [appwrite/sdk-for-node#16] opened 2021-06-08 18:55 UTC
I tried to create a collection inside of a function but instead, of it creating a collection I get this error. 

TypeError: Cannot read property 'statusText' of undefined
    at Client.call (/usr/local/src/node_modules/node-appwrite/lib/client.js:163:64)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Database.createCollection (/usr/local/src/node_modules/node-appwrite/lib/services/database.js:94:16)

**Comment by eldadfux** [comment] 2021-06-09 04:19
@lohanidamodar my guess is that this is a problem parsing a non-json error message.

@cambo2015 are you sure your'e using the correct endpoint hostname to allow you to connect with Appwrite?
What does your code look like?

**Comment by eldadfux** [comment] 2021-06-09 04:21
For accessing your Appwrite instance from within the function runtime you could use: `http://host.docker.internal/v1` as the Appwrite endpoint.

**Comment by lohanidamodar** [comment] 2021-06-09 06:52
> @lohanidamodar my guess is that this is a problem parsing a non-json error message.
> 
> @cambo2015 are you sure your'e using the correct endpoint hostname to allow you to connect with Appwrite?
> What does your code look like?

Yes the error is because of that, but not sure of a condition to reproduce it. Code would be helpful in reproducing and fixing

@cambo2015 can you share the code you are trying to execute

@TorstenDittmann would also appreciate your help when you are available.

**Comment by cambo2015** [comment] 2021-06-09 15:43
Thanks, everyone. Give me a minute and I will share it.

**Comment by cambo2015** [comment] 2021-06-09 15:44
```javascript
database
    .createCollection(
      "user-info",
      ["*"],
      ["*"],
      [
        {
          key: "User Id",
          label: "User Id",
          type: "text",
          default: "",
          required: true,
          array: false,
        },
        {
          key: "stripeId",
          label: "Stripe Id",
          type: "text",
          default: "",
          required: true,
          array: false,
        },
        {
          key: "paid",
          label: "Paid",
          type: "boolean",
          default: false,
          required: true,
          array: false,
        },
      ]
    )
    .then((x) => {
      if (!x) {
        console.log("db collection not created")
        return
      }
      console.log(`x exists ${x}`)
      return
    })
    .catch((error) => {
      console.log(error)
      return
    })
```

**Comment by cambo2015** [comment] 2021-06-09 15:52
@eldadfux yes I am sure. It was executing but still gave me that error.  I ended up deleting that server and started a new instance via digital ocean. After that, the error went away when I added selfsigned() after the setKey() and I changed to nodejs 15.5 on my local machine.

**Comment by cambo2015** [comment] 2021-06-09 15:54
here is the order I executed it. I remove my keys 
```javascript
client
  .setEndpoint()
  .setProject()
  .setKey(
   
  ).setSelfSigned()
```

**Comment by cambo2015** [comment] 2021-06-09 15:58
here is the entire code 
```javascript
const sdk = require("node-appwrite")
const data = JSON.parse(process.env.APPWRITE_FUNCTION_EVENT_DATA)
const { name, email } = data
const logger = []

const client = new sdk.Client()
client
  .setEndpoint()
  .setProject()
  .setKey(
   
  ).setSelfSigned()

const database = new sdk.Database(client)

const main =  () => {
  return  database
    .createCollection(
      "user-info",
      ["*"],
      ["*"],
      [
        {
          key: "User Id",
          label: "User Id",
          type: "text",
          default: "",
          required: true,
          array: false,
        },
        {
          key: "stripeId",
          label: "Stripe Id",
          type: "text",
          default: "",
          required: true,
          array: false,
        },
        {
          key: "paid",
          label: "Paid",
          type: "boolean",
          default: false,
          required: true,
          array: false,
        },
      ]
    )
    .then((x) => {
      if (!x) {
        console.log("db collection not created")
        return
      }
      console.log(`x exists ${x}`)
      return
    })
    .catch((error) => {
      console.log(error)
      return
    })
}

main()



```

**Comment by cambo2015** [comment] 2021-06-09 17:44
Yes, I still encounter errors. I just tried to add process.env.APPWRITE_FUNCTION_EVENT_DATA to my file but it produced undesired behavior. It worked until this.  Here is the result ->  I added process.env.APPWRITE_FUNCTION_EVENT_DATA to my file. The function results said that the name and the email attributes were undefined. Then I created a new user and didn't get anything. The function did not finish running. I will check docker doctor and see if anything is down.

**Comment by cambo2015** [comment] 2021-06-09 17:47
here is the code for this new function I made. Again I left keys out.
```javascript 
const sdk = require("node-appwrite")

const data = JSON.parse(process.env.APPWRITE_FUNCTION_EVENT_DATA)

const {name,email} = data
//variables
const colName = "user-info"



const client = new sdk.Client()
client
  .setEndpoint()
  .setProject()
  .setKey()

const database = new sdk.Database(client)



/**
 * @description inserts a doc into a collection via colId
 * @param {String} colId 
 */
const createDoc = async (colId) => {
    await database.createDocument(colId, {
        userId: data['$id'],
        
    }, ["*"], ["*"]).then(x => {
        if (x !== null || x !== undefined) console.log(' document is undefined')
        console.log(`success! Document created`)
    }).catch(error=>console.error(error))
}


/**
 * @description creates collection and inserts doc into collection
 */
const createBoth = async () => {
    await database.createCollection(
        colName,
        ["*"],
        ["*"],
        [
          {
            type: "text",
            key: "name",
            label: "name",
            required: true,
            array: false,
          },
        ]
    ).then((db)=> {
        const id = db['$id']
        createDoc(id)
    } ).catch(error=>console.error(error))
}


database
  .listCollections()
  .then((db) => {
    if (Array.isArray(db.collections)) {
      const temp = db.collections.filter((obj) => obj.name === colName) //will return an empty arr if nothing found
  

      if (temp.length > 0) {
        //exists //insert into array
          const id = temp[0]['$id']
          createDoc(id)
         
      } else {
        //does not exist so create both 
        createBoth()
      }
    } else {
      // console.log(typeof db)
      console.error("code 500. db.collections not an array")
    }
  })

  .catch((error) => console.error(error))
```

**Comment by cambo2015** [comment] 2021-06-09 18:09
I also tried just the event env variable by itself and it works without errors:
```javascript
const sdk = require("node-appwrite")
const data = JSON.parse(process.env.APPWRITE_FUNCTION_EVENT_DATA)

const client = new sdk.Client()
client
  .setEndpoint()
  .setProject()
  .setKey()
  .setSelfSigned()

console.log(data["$id"])

```

**Comment by cambo2015** [comment] 2021-06-09 18:10
Hopefully, this is enough info. Let me know if you need more

**Comment by sendyputra** [comment] 2021-06-20 18:41
i got this bug too for database.updateDocument refer from this post https://dev.to/appwrite/30daysofappwrite-our-first-cloud-function-59k6

here is my code

```javascript
console.log("env", process.env);
const DATA = JSON.parse(process.env.APPWRITE_FUNCTION_EVENT_DATA);
const POSTS_COLLECTION = process.env.POSTS_COLLECTION;
console.log("data", DATA);
const { $id, $collection, text, published } = DATA;

// Stop if it's not the Posts Collection or not published
if ($collection !== POSTS_COLLECTION || !published) {
  return;
}

// Initialise the client SDK
const appwrite = require("node-appwrite");
const client = new appwrite.Client();
const database = new appwrite.Database(client);

client
  .setEndpoint(process.env.APPWRITE_ENDPOINT) // Your API Endpoint
  .setProject(process.env.APPWRITE_PROJECT_ID) // Your project ID
  .setKey(process.env.APPWRITE_API_KEY); // Your secret API key

// Get word count
let words = text.match(
  /[A-Za-z\u00C0-\u017F]+|[\u0400-\u04FF\u0500–\u052F]+|[\u0370-\u03FF\u1F00-\u1FFF]+|[\u4E00–\u9FFF]|\d+/g
);

words = words ? words.length : 0;

let minutes = words / 200;
let seconds = (minutes % 1) * 60;
let readingTime = `${Math.floor(minutes)}m ${Math.floor(seconds)}s`;

// Don't update Post if reading time has not changed
if (readingTime === DATA.readingTime) {
  return;
}

console.log("readingTime", readingTime);

database
  .updateDocument($collection, $id, {
    readingTime: "123 s",
  })
  .then((res) => {
    console.log("update response", res);
  })
  .catch((err) => {
    console.log("update catch", { $collection, $id }, err);
  });

```

and here stdout from event executions

```javascript
env {
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  HOSTNAME: 'd4d0c88ada26',
  APPWRITE_FUNCTION_TRIGGER: 'event',
  APPWRITE_FUNCTION_PROJECT_ID: '60cf083f04299',
  APPWRITE_ENDPOINT: 'http://localhost:3003/v1',
  APPWRITE_API_KEY: 'b807b5e1bb8dc3f3011a067b7ec87c3a9e91a2a2f1531b66234d53f8a547bdb13fd41ed8dce672ad921857a687ff6561eb4a64dbd2135e410c0019e14fdb20b48987e2e24694a395478f6187d080320ec7b866c50ee0ec8bda27709aef48763da5990ad49965b17f256c4edb705cc21430ac07a3090296c219cbb44d5fd8c594',
  APPWRITE_FUNCTION_TAG: '60cf8a7944789',
  APPWRITE_FUNCTION_RUNTIME_VERSION: '15.5',
  APPWRITE_FUNCTION_EVENT: 'database.documents.update',
  APPWRITE_FUNCTION_DATA: 'null',
  APPWRITE_PROJECT_ID: '60cf083f04299',
  POSTS_COLLECTION: '60cf0baee1c4c',
  APPWRITE_FUNCTION_ID: '60cf760fd2c84',
  APPWRITE_FUNCTION_EVENT_DATA: '{"$id":"60cf73401b745","$permissions":{"read":["*"],"write":["*"]},"$collection":"60cf0baee1c4c","title":"Squeaky-Clean Eating","text":"test reading time too asd","readingTime":"","published":true}',
  APPWRITE_FUNCTION_JWT: 'null',
  APPWRITE_FUNCTION_NAME: 'Reading Time',
  APPWRITE_FUNCTION_RUNTIME_NAME: 'Node.js',
  APPWRITE_FUNCTION_USER_ID: 'admin-60cf080952f26',
  NODE_VERSION: '15.5.1',
  YARN_VERSION: '1.22.5',
  HOME: '/root'
}
data {
  '$id': '60cf73401b745',
  '$permissions': { read: [ '*' ], write: [ '*' ] },
  '$collection': '60cf0baee1c4c',
  title: 'Squeaky-Clean Eating',
  text: 'test reading time too asd',
  readingTime: '',
  published: true
}
readingTime 0m 1s
update catch { '$collection': '60cf0baee1c4c', '$id': '60cf73401b745' } TypeError: Cannot read property 'status' of undefined
    at Client.call (/usr/local/src/node_modules/node-appwrite/lib/client.js:163:80)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Database.updateDocument (/usr/local/src/node_modules/node-appwrite/lib/services/database.js:380:16)

```

**Comment by sendyputra** [comment] 2021-06-21 09:27
> For accessing your Appwrite instance from within the function runtime you could use: `http://host.docker.internal/v1` as the Appwrite endpoint.

i got fix this bug with setEndpoint to local ip address, while try using http://host.docker.internal/v1 execution always waiting

**Comment by jordan-hamilton** [comment] 2021-07-21 15:09
I noticed this same error when executing a Node 16 function from the admin console, as soon as that function tries to list documents in a collection. This happens regardless of the endpoint I set in the client (IP address, localhost, or host.docker.internal) and using HTTP, or using HTTPS combined with setSelfSigned(true). I've only noticed this from a Docker installation on Windows, after successfully using the same function with an installation on 2 different Macs. I tried turning Windows Firewall off and accepted all defaults on the Appwrite installation, so the .env and docker-compose.yaml file are the default values for a new installation of 0.9.1.

When I replace the [call function's catch block in client.js](https://github.com/appwrite/sdk-for-node/blob/d25d795e677f03656a02e841f9af58ea722dd0da/lib/client.js#L154-L168) with console.error(error), this is the result:
```
e,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/v1/database/collections/60f723eeb608c/documents?limit=1&offset=0&orderField=date&orderType=DESC',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/database/collections/60f723eeb608c/documents',
      search: '?limit=1&offset=0&orderField=date&orderType=DESC'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /v1/database/collections/60f723eeb608c/documents?limit=1&offset=0&orderField=date&orderType=DESC HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'x-sdk-version: appwrite:nodejs:2.4.0\r\n' +
        'X-Appwrite-Response-Format: 0.9.0\r\n' +
        'x-appwrite-project: 60f723bebd262\r\n' +
        'x-appwrite-key: [OMITTED]\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/database/collections/60f723eeb608c/documents?limit=1&offset=0&orderField=date&orderType=DESC',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost/v1/database/collections/60f723eeb608c/documents?limit=1&offset=0&orderField=date&orderType=DESC',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
An error occurred.
```

Prior to removing the exception throwing from the catch block, my result was this:
```
Error:  TypeError: Cannot read property 'statusText' of undefined
    at Client.call (/usr/local/src/node_modules/node-appwrite/lib/client.js:163:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Database.listDocuments (/usr/local/src/node_modules/node-appwrite/lib/services/database.js:246:16)
    at async downloadObjects (file:///usr/local/src/index.js:92:24)
    at async main (file:///usr/local/src/index.js:231:17)
```

You can see that the response property is in the error, but undefined, which explains the TypeError for statusText: https://github.com/appwrite/sdk-for-node/blob/d25d795e677f03656a02e841f9af58ea722dd0da/lib/client.js#L163

I'm still at a loss as to why the call is failing in the first place, and where I would go about debugging that. Thanks in advance for any assistance!

---
Appwrite Version: 0.9.1.149

**Comment by lohanidamodar** [comment] 2022-02-11 05:45
Closing this as there's been no new activity for long time, feel free to reopen if the issue still exist.

**Closed by lohanidamodar** 2022-02-11 05:45 UTC
